### ISSUE TITLE
Typing sounds not present in Google Docs

### ISSUE THREAD

**Issue by TheDragonsFlame** [noblereign/GX-Mods-Extension#1]
Quick sidenote, I would like to mention that I am immensely pleased to find that a furry created/maintains this extension, you've earned my confidence

Typing in the page section of google docs does not seem to activate keyboard sounds, which is admittedly one of the main reasons why I installed the extension. Other textboxes seem to work, just not this particular one

https://github.com/noblereign/GX-Mods-Extension/assets/42993952/3f8b0562-21b3-4e45-8bd6-609f7bf31099

**Comment by noblereign** [comment]
oh god i see why this might be happening
google docs uses like... some sort of svg canvas trickery to handle the document area instead of just a normal input
i'm guessing it's eating the keydown event while doin that somehow
i'll see if i can figure it out 😵‍💫

**Comment by noblereign** [comment]
oh nevermind it was just an iframe i just had to change the manifest a bit lol
this'll be fixed in a moment 👍
