### ISSUE TITLE
"Failed to encode"

### ISSUE THREAD

**Issue by flowwtcity** [noblereign/GX-Mods-Extension#13]
**Describe the issue**
I can not install a particular mod

**To Reproduce**
1. Go to https://store.gx.me/mods/ot1jje/akko-lavender-purple/
2. Click on 'Install with GXM'
3. It failed to encode

**Expected behavior**
The mod installs on my browser

**Screenshots**
![image](https://github.com/noblereign/GX-Mods-Extension/assets/164115356/f844b480-8fc2-4deb-abac-5881c10ddb8e)

**System Information**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 124.0.1

**Comment by noblereign** [comment]
sorry for the slow response time, i had seen the e-mail for the issue right as i was about to pass out (i was very tired)
![image](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/19c7d6f0-1225-4e51-964e-cfb63cf1448c)
seems like the server is forbidding the file from being downloaded, i'll look into this further rn

**Comment by noblereign** [comment]
i don't think this is something i can fix on my end? i even tried opening it in the actual Opera GX browser and the requests still failed. it's probably misconfiguration on Opera's side, so i'm completely out of luck here 😓  

nevertheless, i did a quick lookup and found out that someone's already extracted the files from the mod you wanted. you can download the files from [this repo](https://github.com/FireXDragon007/Akko-Lavender-Purple-Mechvibes-customs-) and create a local mod as a workaround.

sorry that this isn't really "solved", but i think i'm powerless for this one 😭

**Comment by flowwtcity** [comment]
Thanks so much for checking this out and getting back to me! 

Do you happen to have a guide on how to make a local mod as a workaround? i'm a noob

**Comment by noblereign** [comment]
> Thanks so much for checking this out and getting back to me!
> 
> Do you happen to have a guide on how to make a local mod as a workaround? i'm a noob

dont worry i got you, i'll explain it from the beginning

so first off you're gonna want to go to the place to download all the sounds: https://github.com/FireXDragon007/Akko-Lavender-Purple-Mechvibes-customs-

once you're there you're gonna wanna hit the green "Code" button, then the "Download zip" button
![firefox_78099](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/c9064790-c9c1-4df1-8579-463609210930)

once that's downloaded, go ahead and open it. you should see a single folder in there called "Akko-Lavender-Purple-Mechvibes-customs-".

drag that somewhere else on your computer. for my example i'll do a folder on my desktop.

![explorer_78101](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/4d14ff7a-73a6-40be-ada4-6df6afeb68c5)

once that's done, go back to Firefox and open the settings menu for GXM.
scroll aaaalll the way down...
![Screenshot_78102](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/be17dbb5-4bbe-4758-b09e-a1b0060c85c2)

...'til you see the "Mods" button.
![Screenshot_78103](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/9f37af29-1299-4e0b-ab47-3781fc120a65)

give that a click and you'll end up in the Mod Manager.
at the bottom of this page you should see the "Create" button. scroll down if you have to!
![firefox_78104](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/01c4870a-e1c7-4477-8fb9-458435665fd6)

that'll open up the mod creation screen. 
go ahead and name the mod. once you've done that, go down to the "Sound effects" section and click "Choose files".
![firefox_78105](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/c8a20c21-a3e6-4687-837b-d134b0d5b867)

find that "Akko-Lavender-Purple-Mechvibes-customs-" folder from the previous step. you'll see a bunch of .wav files in there.
just select everything in there (either by dragging the mouse over everything, or `CTRL + A`) and hit "Open" on the bottom right.
![firefox_78106](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/33eff174-2cfc-4bda-bacf-ea70d0cb8998)

you should see all the files appear in the sound effects section. 
all of them will have a dropdown next to them saying "- select an option -". for each one, click on the dropdown and set the sound type appropriately
![firefox_78107](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/59fee5e5-18b2-4267-822a-2d9bf67476a0)

hit the big red "Create" button, and you should see your mod appear in the list!
![firefox_78108](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/4817659c-caba-4ac7-9de3-0e5496217498)

finally, re-open the GXM settings, scroll aaalll the way down to the Keyboard Sounds section, and pick your mod from the dropdown.
![firefox_78109](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/c0ad2212-dec9-481a-85b5-bfad1cbbb58b)

you should be all set after that! ^^
