### ISSUE TITLE
Failed to encode.

### ISSUE THREAD

**Issue by FaboDude** [noblereign/GX-Mods-Extension#15]
I have the extension installed and whenever I click Install with GMX it says failed to encode.

**To Reproduce**
1. Go to 'https://store.gx.me/mods/a7t0tm/official-cyberpunk-2077/'
2. Click on 'Install with GMX'
3. Failed to encode.

**Expected behavior**
Installs the mod.

**Screenshots**
![image](https://github.com/noblereign/GX-Mods-Extension/assets/167238130/b71579ce-147f-451c-b24c-b5d3f2179ade)

**System Information**
 - OS: Windows 11
 - Browser [e.g. Firefox]
 - Version 125.0.1

**Comment by noblereign** [comment]
ah, i see what's going on here.
this is the first mod i've seen that does this, it seems to use a completely different format to store the background music.
i'll need to grab my laptop to see how this acts in actual Opera GX, and then i can work on fixing this
![image](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/6622bd75-57a7-4658-bfef-44b299db7299)

**Comment by noblereign** [comment]
ah, no wonder, seems like this might be a recent feature -- my laptop's GX was oudated enough it told me to "Try on Opera GX Desktop" even though i was already on Opera GX 💀

**Comment by noblereign** [comment]
yeah this issue seems like it was partly the mod format being newer and partly Opera just blocking GXM, i'm currently knee-deep into figuring this out and it's kinda complicated to get around (if i can even do so at all)
i might have to entirely rewrite how mods are downloaded for this since it's been an hour and i havent had any luck getting past the 403 unauthorized 😭

**Comment by noblereign** [comment]
day 2 of not being able to get past the 403 errors 😭

**Comment by noblereign** [comment]
IM FREEEE
![image](https://github.com/noblereign/GX-Mods-Extension/assets/2935979/8cfb7072-40ab-44f8-bfd9-35835d58b662)
gonna do a bit more testing then i can push this out

**Comment by noblereign** [comment]
just submitted 5.0.0 to AMO, once you're able to update it should resolve the issue! thank you for your patience!! ^^

**Comment by FaboDude** [comment]
Thanks, everything seems to be working fine now.
