### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by mcortt** [noblereign/GX-Mods-Extension#21]
**Describe your cool new feature!**
Can you add keyboard shortcuts for the toggles (via Firefox extension menus).
* For Background music on/off
* For Keyboard sounds on/off
* For all on/off

**Comment by noblereign** [comment]
sounds easy enough, I'll get around to it in the next update

**Comment by noblereign** [comment]
6.3.0 is released on the addon store which adds this feature, i hope this satisfies the request!
if you have any other shortcuts you'd like to see i can try and add them :)

**Comment by mcortt** [comment]
> 6.3.0 is released on the addon store which adds this feature, i hope this satisfies the request! if you have any other shortcuts you'd like to see i can try and add them :)

Wow very fast turn around. Really appreciate this!
