### ISSUE TITLE
Not an Issue but thank you

### ISSUE THREAD

**Issue by Deleca7755** [noblereign/GX-Mods-Extension#25]
I can finally use Firefox. 

I got really attached to the custom typing sounds I set. Since the Manifest V3 thing Is happening and all, and I always liked Firefox anyway, I wanted to switch from Opera GX. I couldn't because this customization mattered a lot to me

I was honest to god going to ( attempt to... ) make a typing sounds extension myself because I couldn't find one that existed

Apparently not? This gem was just hiding from me? Allows Importing real GX mods and all?

I'm ecstatic, Typing this and hearing my sounds despite not being In GX

Thank you. Wholeheartedly. It works flawlessly, besides the little address bar quirk

Sorry If this "Issue" Is... an Issue. I just wanted to show my gratitude and this was the most convenient way for me

**Comment by Deleca7755** [comment]
Wait literally this Is what firefox reviews are for. Guess I got too excited about It

oh well, still : ) I'll be sure to leave one though

**Comment by noblereign** [comment]
haha, no worries about the issue, i've done the same before :p
i'm glad that i was able to help and make your day better! ^^
