### ISSUE TITLE
Rename "Layers" in mod creation to "Background Music" to prevent confusion

### ISSUE THREAD

**Issue by Aelesto74** [noblereign/GX-Mods-Extension#26]
Helloooo!

I was editing some music to add to GX Mods until I realized that there's not an option for that, you can only put sound effects and **not background music** (_unless it is from the GX Store ofc_). I'd love to add my own multitracked music into the mod, but it either requires me **to create a GX account** (which I really wouldn't want to do), **to manually program the files** into the mod myself (which I would love to know how to do it), or for you **to add it as a feature** into the mod (maybe it's possible but I can see why it's difficult).

Could you maybe guide me how to import my songs into the mod locally, like you did for the built-in music? I would really appreciate that.

Thanks in advance
_-Aelesto_

**Comment by noblereign** [comment]
I think you can already do what you're asking for by going to the Mod Manager, scrolling all the way to the bottom, and hitting "Create" 
from there you can add the layers of the background music to the "Layers" section
sorry for the vertical screenshots, I'm on my phone atm

![Screenshot_20240905-124956.png](https://github.com/user-attachments/assets/a73617d4-3d21-41e3-b367-5b28005f722d)

![Screenshot_20240905-125010.png](https://github.com/user-attachments/assets/54c2e039-080c-4598-8fa6-dc0739920376)

**Comment by noblereign** [comment]
the name is a holdover from back when the extension could only do music, I'll probably change it the next time I update
thank you for bringing that up and I hope you have fun using gxm ^^

**Comment by noblereign** [comment]
changed up the wording in 6.4.0, which is [out now](https://addons.mozilla.org/en-US/firefox/addon/gx-mods/)! sorry for the long wait :smiling\_face\_with\_tear:
