### ISSUE TITLE
Mods fail to install due to missing file variants

### ISSUE THREAD

**Issue by wojtal1** [noblereign/GX-Mods-Extension#28]
This mod [https://store.gx.me/mods/3or9qd/omori-headspace-normal-/](here) says it fails to encode.

**Comment by noblereign** [comment]
ah, it seems like some of the sound effects return a 403 unauthorized error when trying to download them.

looking into it a little further i may have spotted a potential fix to stop these kinds of errors from occurring. basically, i think that some mods say that they're supposed to have some files, but the files don't actually exist. 

![](https://github.com/user-attachments/assets/ea2a4f84-f7ab-43c3-8022-284edd930019)

i can likely get around to implementing this fix in the next update. i don't know for certain if there are actually sound effects for these broken files though, i don't have an Opera GX installation to check with :sweat\_smile:

**Comment by noblereign** [comment]
this should be fixed in 6.4.0, which is [out now](https://addons.mozilla.org/en-US/firefox/addon/gx-mods/)! sorry for the long wait :smiling\_face\_with\_tear:
