### ISSUE TITLE
Failed donwloading Stardew Valley

### ISSUE THREAD

**Issue by Peperehobbits01** [noblereign/GX-Mods-Extension#32]
**Describe the issue**
I tried to install a the Stardew Valley mod on the GX mods store and it didn't work it said failed donwload

**To Reproduce**
1. Go to GX mods
2. Search for Stardew Valley and pick the first one
3. Try to donwload, it failes, try again and again same thing. Dosen't hapen whit other mods for some reason.

**Expected behavior**
Well that I could donwload the mods... on my newer version of Linux Mint.

**System Information**
 - OS: Linux Mint 22
 - Browser : Firefox
 - Version : 130

**Comment by noblereign** [comment]
this should be fixed in 6.4.0, which is [out now](https://addons.mozilla.org/en-US/firefox/addon/gx-mods/)! sorry for the long wait :smiling\_face\_with\_tear:

**Comment by Peperehobbits01** [comment]
Dont worry, I have some busy weeks to. I know it's hard.
