### ISSUE TITLE
Failure to download Dreamcast mod

### ISSUE THREAD

**Issue by IcedTeaYouGive** [noblereign/GX-Mods-Extension#33]
From my testing (which is pretty limited, I only tried downloading the Dreamcast mod) this extension seems to fail to download larger mods from the GX Store. I've personally only seen this with the Dreamcast theme, might be a singular problem, but I prefer to cover all bases.

**Comment by noblereign** [comment]
just checked the dreamcast mod and bro what is thiiiis??? 😭

![](https://github.com/user-attachments/assets/46c485d7-1674-4c93-a279-d9d92d50daf2)

this mod just straight up has invalid metadata. those sound effects are pointing directly to a folder. diabolical 😭

im working on fixing this rn, hopefully will be able to come back soon with an update

**Comment by noblereign** [comment]
this should be fixed in 6.4.0, which is [out now](https://addons.mozilla.org/en-US/firefox/addon/gx-mods/)! sorry for the long wait :smiling\_face\_with\_tear:
